/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as React from "react";
import { useGLTF } from "@react-three/drei";

export default function GltfModel({ ...props }) {
  console.log(props);
  // const group = useRef();
  // console.log(capstone-website/src/server_fileuploader/public/model.glb);
  const { nodes, materials } = useGLTF("/model.glb");
  console.log(nodes, materials)
  const rotatedGeometry = nodes.mesh_0.geometry;
  rotatedGeometry.computeVertexNormals();
  const mat = nodes.mesh_0.material;
  mat.flatShading = false;

  return (
    // <group ref={group} dispose={null} {...props}>
      <mesh 
        position={props.position}
        onClick={props.onClick}
        scale={props.scale}
        // {...props}
        rotation={[0, props.rotation, 0]}
        castShadow
        receiveShadow
        geometry={rotatedGeometry}
        material={mat}
      />
    // </group>
  );
}

useGLTF.preload("/model.glb");